### ISSUE TITLE
Multi-users on a single port

### ISSUE THREAD

**Issue by josefredohd** [ypo777/Shell_Scripts#1]
Is this possible?

**Comment by ypo777** [comment]
Yep You can use multi-users on a single port but I have not tested how many users you can use ?

**Comment by josefredohd** [comment]
Can you set a time limit and GB for each user?

**Comment by ypo777** [comment]
Sorry I can't help you with that because I am not the original creator of x-ui. 
You can ask [here](https://github.com/vaxilu/x-ui).

**Comment by khalequzzaman17** [comment]
The web UI comes with English? Or, is it in the Chinese language?

One more thing, please consider working on a WHMCS module, for managing VPN users (plans, provision of VPN user, suspend, renew etc)

**Comment by ypo777** [comment]
I think WebUI came with Chinese Language. 
If you want to request more functions , go to [x-ui](https://github.com/vaxilu/x-ui).
